### ISSUE TITLE
Module not working if follow instruction

### ISSUE THREAD

**Issue by amigo00678** [navinpeiris/ng-country-select#2]
I followed the instruction to use module but got not working module. Maybe something else is needed?

![country](https://cloud.githubusercontent.com/assets/16753072/13311018/4d217e0e-dbb5-11e5-8801-38df38af4731.png)

**Comment by amigo00678** [comment]
Fixed this by replacing template with folowing:

`template: '<select><option ng-repeat="country in countries" value="country.code">{{country.name}}</option></select>',`

**Comment by hsilvest** [comment]
you forgot the "{{}}" at values 

`template: '<select><option ng-repeat="country in countries" value="{{country.code}}">{{country.name}}</option></select>',`

**Comment by ashkarrrahman** [comment]
@hsilvest :+1:

**Comment by donato-francavilla** [comment]
@amigo00678, don't modify the module, add an ng-model to the tag:

`<country-select ng-model="country" cs-priorities="GB, US, CN, ES"></country-select>`

**Comment by daijaafarflyt** [comment]
angular app not detecting the 'country-select' tag
